dataset:
  max_chunk_length: 2.0
  min_chunk_length: 2.0
  aug_cfg: conf/reverb_noise_aug.yaml 
sampler:
  batch_size: 32 # 64 oom w/ lresnet34 in this version of hyperion (It wasn't in the old version). Thus, 32 w/ 4 gpu instead of 64 w/ 2 gpu
  iters_per_epoch: 1
data_loader:
  num_workers: 8
  
