data:
  train: train_data_default.yaml
  val: val_data_default.yaml
model:
  xvector:
    cos_scale: 32.0
    margin: 0.2
    margin_warmup_epochs: 0
    intertop_k: 5
    intertop_margin: 0.1
trainer: trainer_phase2_sgd_default.yaml
 