optim:
  opt_type: sgd
  lr: 5.5e-3
  momentum: 0.9
  weight_decay: 1e-4
lrsched:
  lrsch_type: exp_lr
  decay_rate: 0.5
  decay_steps: 5000
  hold_steps: 6000
  min_lr: 4.4e-3
  warmup_steps: 6000
  update_lr_on_opt_step: true
use_amp: true
log_interval: 1000
epochs: 7
eff_batch_size: 512
train_mode: full
