data:
  train:
    dataset:
      max_chunk_length: 6.0
      min_chunk_length: 6.0
      aug_cfg: conf/reverb_noise_aug.yaml
      wav_scale: 1
    sampler:
      batch_size: 32
      iters_per_epoch: 6
    data_loader:
      num_workers: 8
  val:
    dataset:
      max_chunk_length: 4.0
      min_chunk_length: 4.0
      aug_cfg: conf/reverb_noise_aug.yaml
      wav_scale: 1
    sampler:
      batch_size: 32
      iters_per_epoch: 6
    data_loader:
      num_workers: 8
model:
  xvector:
    cos_scale: 32.0
    margin: 0.4
    margin_warmup_epochs: 0
    intertop_margin: 0.1
trainer:
  optim:
    opt_type: sgd
    lr: 2.3e-4
    momentum: 0.9
    weight_decay: 1e-4
  lrsched:
    lrsch_type: exp_lr
    decay_rate: 0.5
    decay_steps: 5000
    hold_steps: 6000
    min_lr: 2e-4
    warmup_steps: 6000
    update_lr_on_opt_step: true
  use_amp: true
  log_interval: 1000
  epochs: 2
  eff_batch_size: 192
  train_mode: full

 